{{- if .Values.mariadb.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sync-in.mariadb-svc" . }}
  labels:
    {{- include "sync-in.labels" . | nindent 4 }}
    app.kubernetes.io/component: mariadb
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "sync-in.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mariadb
  template:
    metadata:
      labels:
        {{- include "sync-in.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mariadb
    spec:
      securityContext:
        {{- toYaml .Values.mariadb.podSecurityContext | nindent 8 }}
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"
          imagePullPolicy: {{ .Values.mariadb.image.pullPolicy }}
          command:
            - docker-entrypoint.sh
            {{- range .Values.mariadb.commandArgs }}
            - {{ . }}
            {{- end }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "sync-in.fullname" . }}-mariadb
                  key: root-password
            - name: MYSQL_DATABASE
              value: {{ .Values.mariadb.database | quote }}
          ports:
            - name: mysql
              containerPort: 3306
              protocol: TCP
          securityContext:
            {{- toYaml .Values.mariadb.securityContext | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
          resources:
            {{- toYaml .Values.mariadb.resources | nindent 12 }}
      volumes:
        - name: data
          {{- if .Values.mariadb.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "sync-in.mariadb-svc" . }}
          {{- else }}
          emptyDir: {}
          {{- end }}
      {{- with .Values.mariadb.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.mariadb.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
