apiVersion: v1
kind: Service
metadata:
  name: {{ include "sync-in.nginx-name" . }}
  labels:
    {{- include "sync-in.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  selector:
    {{- include "sync-in.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
